spring:
  #数据源配置
  datasource:
    username: "biosphere"
    password: "yi89853901yi"
    url: jdbc:mysql://124.221.252.162:3306/biosphere?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #    url: jdbc:mysql://localhost:3306/biosphere?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    #连接池名
    pool-name: HikariCP
    #最小空闲连接数
    minimum-idle: 10
    #空闲连接存货最大时间，默认600000(10min)
    idle-timeout: 60000
    #最大连接数，默认10
    maximum-pool-size: 10
    #从连接池返回的连接自动提交
    auto-commit: true
    #连接最大存活时间，0表示永久存货，默认1800000(30min)
    max-lifetime: 60000
    #连接超时时间，默认30000(30s)
    connection-timeout: 60000
    #测试链接是否可用的查询语句
    connection-test-query: SELECT 1