spring:
  profiles:
#    active: pord
    active: dev

#Mybatis-plus配置
mybatis-plus:
  #配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置Mybatis数据返回类型别名(默认别名是类名)
  type-aliases-package: com.biosphere.library.pojo


server:
  port: ${PORT:9002}

